/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-11-22 18:37:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html5>\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>BallonBases</title>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t<h1><a href=\"#\">BallonBases</a></h1>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"search\">\r\n");
      out.write("\t\t\t<form method=\"get\" action=\"\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end #header -->\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"current_page_item\"><a href=\"#\">Inicio</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"indexTorneo.jsp\">Torneos</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"indexEquipo.jsp\">Equipos</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Jugador</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end #menu -->\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t<div id=\"page-bgtop\">\r\n");
      out.write("\t\t\t<div id=\"page-bgbtm\">\r\n");
      out.write("\t\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"title\"><a href=\"#\">Bienvendio a BallonBases </a></h2>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"meta\">Ultima Publicacion <a href=\"#\"></a> el 23 Noviembre, 2017\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&bull;&nbsp; <a href=\"#\" class=\"comments\">Comentarios (0)</a> &nbsp;&bull;&nbsp; <a href=\"#\" class=\"permalink\">Article</a></p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"entry\">\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<p>El baloncesto o básquetbol proviene del Inglés basket (canasta) y ball (pelota). Es un deporte de equipo, en donde dos conjuntos de cinco jugadores cada uno, intentan introducir un balón, el mayor numero de veces posible en una cesta suspendida por encima de sus cabezas y situada en la parte de la cancha del equipo contrario. El básquet es uno de los deportes mas populares, con mayor número de espectadores y participantes en el mundo.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"title\"><a href=\"indexTorneo.html\">Sudamericano. </a></h2>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"meta\">Ultima Publicacion <a href=\"#\"></a> el 23 Noviembre, 2017\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&bull;&nbsp; <a href=\"#\" class=\"comments\">Comentarios (11)</a> &nbsp;&bull;&nbsp; <a href=\"#\" class=\"permalink\">Srticulo</a></p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"entry\">\r\n");
      out.write("\t\t\t\t\t\t\t<p><img src=\"images/img06.png\" width=\"143\" height=\"143\" alt=\"\" class=\"alignleft border\" />La liga Suramericana nace en Buenos Aires Argentina, dándose a conocer por la participación de equipos provenientes de todo Suramérica. Este año se celebra el bicentenario de la Liga Sudamericana, que a sus veinte años ha logrado alto reconocimiento por grandes entidades deprotivas como la NBA. Teniendo como sede principal el país de Colombia. </p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"title\"><a href=\"indexTorneo.html\">Copa Promaster. </a></h2>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"meta\">Ultima Publicacion <a href=\"#\"></a> el 23 Noviembre, 2017\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&bull;&nbsp; <a href=\"#\" class=\"comments\">Comentarios (5)</a> &nbsp;&bull;&nbsp; <a href=\"#\" class=\"permalink\">Articulo</a></p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"entry\">\r\n");
      out.write("\t\t\t\t\t\t\t<p><img src=\"images/img05.jpg\" width=\"143\" height=\"143\" alt=\"\" class=\"alignleft border\" />Una de las Copas más reconocidas a nivel mundial, destacandose por sus grandes jugadores y sus grandes habilidades para el baloncesto, desarrollandose con éxito en el país de Estados Unidos. Este año se celebra su quinceava liga.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"title\"><a href=\"indexTorneo.html\">Liga BBA. </a></h2>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"meta\">Ultima Publicacion <a href=\"#\"></a> el 23 Noviembre, 2017\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&bull;&nbsp; <a href=\"#\" class=\"comments\">Comentarios (8)</a> &nbsp;&bull;&nbsp; <a href=\"#\" class=\"permalink\">Articulo</a></p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"entry\">\r\n");
      out.write("\t\t\t\t\t\t\t<p><img src=\"images/img08.jpg\" width=\"143\" height=\"143\" alt=\"\" class=\"alignleft border\" />La BBA fue la máxima categoría del baloncesto de Bolivia y se convirtió en sucesora de la Copa Simón Bolívar, primer Torneo Nacional Boliviano jugado desde 1960 a 1976. Esta año se celebra el cuaternario. </p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"title\"><a href=\"indexTorneo.html\">Liga Warrior. </a></h2>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"meta\">Ultima Publicacion <a href=\"#\"></a> el 23 Noviembre, 2017\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&bull;&nbsp; <a href=\"#\" class=\"comments\">Comentarios (21)</a> &nbsp;&bull;&nbsp; <a href=\"#\" class=\"permalink\">Articulo</a></p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"entry\">\r\n");
      out.write("\t\t\t\t\t\t\t<p><img src=\"images/Warrior1.png\" width=\"143\" height=\"143\" alt=\"\" class=\"alignleft border\" />La liga Warrior es una de las mas importantes a nivel mundial, por la gran participacion de equipos de gran categoria mundial. En esta oportunidad se celebra su tercera liga consecutiva. </p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"clear: both;\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- end #content -->\r\n");
      out.write("\t\t\t\t<div id=\"sidebar\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>MVP</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p><img src=\"images/mvp.jpg\" width=\"250\" height=\"350\" alt=\"\" class=\"alignleft border\" / ></p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Hola. </p>\r\n");
      out.write("\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Mejor Equipo</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p><img src=\"images/Equipo1.jpg\" width=\"300\" height=\"250\" alt=\"\" class=\"alignleft border\" / ></p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Hola. </p>\r\n");
      out.write("\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Maximo Anotador</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<p><img src=\"images/Goleador1.png\" width=\"300\" height=\"250\" alt=\"\" class=\"alignleft border\" / ></p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Hola. </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- end #sidebar -->\r\n");
      out.write("\t\t\t\t<div style=\"clear: both;\">&nbsp;</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end #page -->\r\n");
      out.write("</div>\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t<p><a></a></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- end #footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
