/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-11-22 18:37:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class indexTorneo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>Torneos</title>\r\n");
      out.write("<link href=\"styletorneo.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t<h1><a href=\"#\"> Torneos </a></h1>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end #header -->\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li ><a href=\"#\">Inicio</a></li>\r\n");
      out.write("\t\t\t<li class=\"current_page_item\"><a href=\"#\">Torneos</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Equipos</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Jugador</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("          \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("     <div class=\"field\" id=\"searchform\">\r\n");
      out.write("     <input type=\"text\" id=\"searchterm\" placeholder=\"Busca un jugador \" />\r\n");
      out.write("     <button type=\"button\" id=\"search\"> Buscar </button>\r\n");
      out.write("     </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div id=\"agregarT\">\r\n");
      out.write("<h3>Agregar un torneo</h3>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("  <form action=\"/action_page.php\">\r\n");
      out.write("    <label for=\"fname\">Nombre torneo</label>\r\n");
      out.write("    <input type=\"text\" id=\"name\" name=\"name\" >\r\n");
      out.write("\r\n");
      out.write("    <label for=\"lname\">Lugar </label>\r\n");
      out.write("    <input type=\"text\" id=\"lugar\" name=\"lugar\" >\r\n");
      out.write("\r\n");
      out.write("    <label for=\"ficture\">Fixture</label>\r\n");
      out.write("    <select id=\"fixture\" name=\"fxcture\">\r\n");
      out.write("      <option value=\"Todos contra todos\">Todos contra todos</option>\r\n");
      out.write("      <option value=\"Elimincacion directa\">Eliminación directa</option>\r\n");
      out.write("    </select>\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"ficture\">Categoria</label>\r\n");
      out.write("    <select id=\"Categoria\" name=\"Categoria\">\r\n");
      out.write("      <option value=\"Masculino 20años\">Masculino 20años</option>\r\n");
      out.write("      <option value=\"Femenino 20años\">Femenino 20años</option>\r\n");
      out.write("      <option value=\"Masculino 15años\">Masculino 15años</option>\r\n");
      out.write("    </select>\r\n");
      out.write("    <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script class=\"cssdeck\" src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
